import { MigrationInterface, QueryRunner } from 'typeorm';

export class createInsertTableProfiles1635608772072 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`INSERT INTO authentication.profiles VALUES (DEFAULT, 'administrator', true, '{"create": ["companies", "managers", "advisors", "brokers", "secretaries", "owners", "customers", "properties", "leads", "businesses"], "read": ["users", "profiles", "companies", "managers", "advisors", "brokers", "secretaries", "owners", "customers", "properties", "leads", "businesses"], "update": ["users", "companies", "managers", "advisors", "brokers", "secretaries", "owners", "customers", "properties", "leads", "businesses"], "delete": ["users", "companies", "managers", "advisors", "brokers", "secretaries", "owners", "customers", "properties", "leads", "businesses"], "amount": ["leads", "businesses"], "search": ["leads", "businesses", "adresses"], "transfer": ["businesses"], "reject": ["businesses"], "close": ["businesses"], "receiveble": ["commissions-receiveble"], "payable": ["commissions-payable"]}', NOW(), NOW())`);
        await queryRunner.query(`INSERT INTO authentication.profiles VALUES (DEFAULT, 'manager', false, '{"create": ["companies", "managers", "advisors", "brokers", "secretaries", "owners", "customers", "properties", "leads", "businesses"], "read": ["users", "profiles", "companies", "managers", "advisors", "brokers", "secretaries", "owners", "customers", "properties", "leads", "businesses"], "update": ["users", "companies", "managers", "advisors", "brokers", "secretaries", "owners", "customers", "properties", "leads", "businesses"], "delete": ["users","companies", "managers", "advisors", "brokers", "secretaries", "owners", "customers", "properties", "leads", "businesses"], "amount": ["leads", "businesses"], "search": ["leads", "businesses", "adresses"], "transfer": ["businesses"], "reject": ["businesses"], "close": ["businesses"], "receiveble": ["commissions-receiveble"], "payable": ["commissions-payable"]}', NOW(), NOW())`);
        await queryRunner.query(`INSERT INTO authentication.profiles VALUES (DEFAULT, 'advisor', false, '{"create": [], "read": ["managers", "owners", "customers", "properties", "leads", "businesses"], "update": ["businesses"], "delete": [], "amount": ["leads", "businesses"], "search": ["leads", "businesses", "adresses"], "transfer": [], "reject": ["businesses"], "close": ["businesses"], "receiveble": [], "payable": []}', NOW(), NOW())`);
        await queryRunner.query(`INSERT INTO authentication.profiles VALUES (DEFAULT, 'broker', false, '{"create": ["owners", "customers", "properties"], "read": ["managers", "secretaries", "owners", "customers", "properties", "leads", "businesses"], "update": ["owners", "customers", "properties", "businesses"], "delete": [], "amount": ["leads", "businesses"], "search": ["leads", "businesses", "adresses"], "transfer": ["businesses"], "reject": [], "close": [], "receiveble": [], "payable": ["commissions-payable"]}', NOW(), NOW())`);
        await queryRunner.query(`INSERT INTO authentication.profiles VALUES (DEFAULT, 'secretary', false, '{"create": ["owners", "customers", "properties", "leads", "businesses"], "read": ["brokers", "owners", "customers", "properties", "leads", "businesses"], "update": ["owners", "customers", "properties", "leads", "businesses"], "delete": ["owners", "customers", "properties", "leads"], "amount": ["leads", "businesses"], "search": ["leads", "businesses", "adresses"], "transfer": ["businesses"], "reject": [], "close": [], "receiveble": [], "payable": []}', NOW(), NOW())`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('TRUNCATE TABLE authentication.profiles');
    }

}
